name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: setup node project
        uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - name: run test
        run: |
          npm run test
